### ISSUE TITLE
[help] Not able to configure ubuntu cloud image

### ISSUE THREAD

**Issue by bilak** [josenk/terraform-provider-esxi#140]
Hello,
I'm trying to install [ubuntu cloud image 20.04](https://cloud-images.ubuntu.com/focal/current/) to esxi 7.0 with following files:

**main.tf**
```
provider "esxi" {
  esxi_hostname = var.esxi_hostname
  esxi_hostport = var.esxi_hostport
  esxi_username = var.esxi_username
  esxi_password = var.esxi_password
}

resource "esxi_guest" "default" {
  guest_name    = var.guest_name
  disk_store    = var.disk_store
  ovf_source    = "/tmp/focal-server-cloudimg-amd64.ova"
  network_interfaces {
    virtual_network = "VM Network"
  }

  guestinfo = {
    "metadata" = base64gzip(file("metadata.yml"))
    "metadata.encoding" = "gzip+base64"
    "userdata" = base64gzip(file("userdata.yml"))
    "userdata.encodinng" = "gzip+base64"
  }
}
```

**metadata.yml**
```
#cloud-config
network:
  version: 2
  ethernets:
    ens160:
      dhcp4: true
      dhcp6: false
      gateway4: 192.168.240.1
      nameservers:
        addresses:
          - 192.168.240.1
```

**userdata.yml**
```
#cloud-config
users:
  - name: test
    lock-passwd: false
    groups: sudo
    plain_text_passwd: test

locale: en_US.UTF-8
timezone: Europe/Prague
hostname: testserver
package_upgrade: true
```

however when I start the machine I'm not able to login with test/test and there is also no network being configured. Before entering login prompt I can see error like on image bellow I think that's related to floppy. I don't know if that can cause some issue or not.

![image](https://user-images.githubusercontent.com/5826062/118402927-555fd880-b66c-11eb-9ab9-3ad9ae16290b.png)

can you please advice what do I have to check? 
ovftool + vmware-guestinfo is installed, I'm using it from docker image

```
FROM ubuntu:20.04
ADD VMware-ovftool-4.4.0-15722219-lin.x86_64.bundle /tmp/ovftool.bundle
RUN apt update && apt install -y \
    cloud-init \
    gnupg \
    software-properties-common \
    curl && \
    cd /tmp && \
    curl -fsSL https://apt.releases.hashicorp.com/gpg | apt-key add - && \
    apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main" && \
    apt update && apt install terraform && \
    curl -sSL https://raw.githubusercontent.com/vmware/cloud-init-vmware-guestinfo/master/install.sh | sh - && \
    /tmp/ovftool.bundle --eulas-agreed && \
    rm -f /tmp/ovftool.bundle && \
    apt autoremove -y && \
    apt clean
```
